### PR TITLE
Merge release candidate into master

### PR DESCRIPTION
**Pull request by thornjad**
This will be the central discussion around the release candidate branch 'rc' leading up to merge into master, which will become version 1.3.

### CODE REVIEW

**Comment by thornjad** [comment]
Gutter is blue for whatever reason

**Comment by thornjad** [comment]
Gutter needed to be overridden with `!important`. This could be because of .gutter style in syntax

**Comment by thornjad** [comment]
Also, auto-complete is having an issue with already-typed letters being smaller than suggestion.

selection_013

**Comment by Raindeer44** [comment]
Autocomplete-Plus checks out

**Comment by Raindeer44** [comment]
Package Build runs without error

**Comment by thornjad** [comment]
Auto-complete is fixed

**Comment by thornjad** [comment]
All relevant issues are fixed. Time to make this the official 1.3.0-rc1

**Comment by thornjad** [comment]
I have so far been unable to find any more issues

**Comment by thornjad** [comment]
Let's run through all `TODO`s next

**Comment by thornjad** [comment]
All `TODO`s are addressed

**Pull request merged**
